services:

  chromadb:
    image: chromadb/chroma:latest

    container_name: chromadb

    restart: unless-stopped

    ports:
      - "8000:8000"

    volumes:
      - ./chromadb:/chroma/chroma

    networks:
      - ai-network

networks:

  ai-network:
