"""
engine.py
---------
Core AI engine.

This module coordinates the complete Retrieval-Augmented Generation (RAG workflow)

Question -> Retriever -> Prompt Builder -> DeepSeek -> Answer

Every interface (CLI, FastAPI, Telegram, Open WebUI) should call this moddule instead of implementing its own AI logic.
"""

from chat.retriever import retrieve
from chat.prompt import build_prompt
from chat.llm import generate

def chat(question: str) -> str:
    """
    Answers a user's question using RAG.

    Parameters
    ----------
    question
        User question.

    Returns
    -------
    str
        Final answer generated by the language model.
    """

    # -----------------------------------
    # Retrieve relevant knowledge
    # -----------------------------------
    chunks = retrieve(question)

    # -----------------------------------
    # Build Prompt
    # -----------------------------------
    prompt = build_prompt(
        question=question,
        chunks=chunks,
    )

    # -------------------------------------
    # Generate answer
    # -------------------------------------
    answer = generate(prompt)

    return answer

