"""
engine.py
---------

Core AI engine.

Coordinates the complete Retrieval-Augmented Generation (RAG)
workflow.

Pipeline

Question
    │
    ▼
Retriever
    │
    ▼
Context Builder
    │
    ▼
Prompt Builder
    │
    ▼
Language Model
    │
    ▼
Answer

Every interface (CLI, FastAPI, Telegram, Open WebUI)
should call this module instead of implementing its own
AI logic.
"""

from chat.retriever import retrieve
from chat.context import build_context
from chat.prompt import build_prompt
from chat.llm import generate
from chat.reranker import rerank


# ============================================================
# Chat Engine
# ============================================================

def chat(question: str) -> str:
    """
    Answer a user's question using Retrieval-Augmented Generation
    (RAG).

    Parameters
    ----------
    question
        User question.

    Returns
    -------
    str
        Final response generated by the language model.
    """

    # --------------------------------------------------------
    # Step 1
    # Retrieve relevant documentation.
    # --------------------------------------------------------

    chunks = retrieve(question)
    chunks = rerank(chunks)

    # --------------------------------------------------------
    # Step 2
    # Convert retrieved chunks into structured context.
    # --------------------------------------------------------

    context = build_context(chunks)

    # --------------------------------------------------------
    # Step 3
    # Build the final prompt.
    # --------------------------------------------------------

    prompt = build_prompt(
        question=question,
        context=context,
    )

    # --------------------------------------------------------
    # Step 4
    # Generate the answer.
    # --------------------------------------------------------

    answer = generate(prompt)

    return answer
